name: almalinux

on:
  push:
  workflow_dispatch:

jobs:
  test:
    runs-on: ${{ matrix.runner }}
    strategy:
      fail-fast: false
      matrix:
        containers: [almalinux:8,almalinux:9]
        runner: [ubuntu-latest,ubuntu-24.04-arm]
    container: ${{matrix.containers}}
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3
      - name: commands
        run: |
            yum update -y
            yum install ffmpeg -y
            ffmpeg -version
