name: Linux Rocky Linux

on:
  push:
  workflow_dispatch:

jobs:
  test:
    runs-on: ${{ matrix.runner }}
    strategy:
      fail-fast: false
      matrix:
        containers: [rockylinux:8,rockylinux:9]
        runner: [ubuntu-latest,ubuntu-24.04-arm]
    container: ${{matrix.containers}}
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3
      - name: commands
        run: |
            dnf update -y
            dnf install -y python3.11
