name: Build Docker Image

on:
  push:
  workflow_dispatch:

jobs:
  build-docker-image:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4

      - name: Build Docker Image
        run: |
          docker build --file solana.Dockerfile . -t solana:latest
      - name: Test Docker Image
        run: |
          docker run --rm solana:latest solana --version